import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "./providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  overflow-hidden`}
      >
        <div className="flex flex-col items-center justify-center w-full bg-gray-100 dark:bg-gray-700 dark:text-white">
          <h1 className="mb-6 text-3xl max-h-5">JSON to CIF</h1>
          <h2 className="text-center text-yellow-500">⚠Vercel url is depricated and redirects to Netlify. ⚠</h2>
          <h2 className="text-center text-green-500">⚠ App itself works as usual. ⚠</h2>
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
